# action.yml
name: 'Redmine Integration'
description: 'update redmine issue'
author: 'thaim'
inputs:
  token:
    description: 'github token'
    required: true
  redmine_host:
    description: 'redmine hostname to integrate with'
    required: true
  redmine_apikey:
    description: 'redmine apikey to use'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
